import { Router } from "express";
import { healthRouter } from "./health";
import { authRouter } from "./auth";
import { categoriesRouter } from "./categories";
import { transactionsRouter } from "./transactions";
import { budgetsRouter } from "./budgets";
import { emailAccountsRouter } from "./emailAccounts";
import { banksRouter } from "./banks";
import { whatsappRouter } from "./whatsapp";
import { categoryRulesRouter } from "./categoryRules";
import { profileRouter } from "./profile";
import { recurringRouter } from "./recurring";
import { goalsRouter } from "./goals";
import { subscriptionRouter } from "./subscription";
import { debtsRouter } from "./debts";

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/categories", categoriesRouter);
apiRouter.use("/transactions", transactionsRouter);
apiRouter.use("/budgets", budgetsRouter);
apiRouter.use("/email-accounts", emailAccountsRouter);
apiRouter.use("/banks", banksRouter);
apiRouter.use("/whatsapp", whatsappRouter);
apiRouter.use("/category-rules", categoryRulesRouter);
apiRouter.use("/profile", profileRouter);
apiRouter.use("/recurring-payments", recurringRouter);
apiRouter.use("/category-goals", goalsRouter);
apiRouter.use("/subscription", subscriptionRouter);
apiRouter.use("/debts", debtsRouter);
